
services:
  postgres: 
    image: postgres:15
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pickup_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/postgres/data

volumes:
  postgres_data: 
  